version: "3.1"

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - "./client/.env"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    build: server/
    command: python ./server.py
    ports:
      - 1234:1234

  tgbot:
    container_name: bot
    build: client/
    command: python ./app.py
    restart: always
    network_mode: "host"
    env_file:
      - "./client/.env"
    depends_on:
      - server
